### ISSUE TITLE
Help Plz!!

### ISSUE THREAD

**Issue by hizagi** [vidyamantra/moodle-local_getkey#1]
Sorry for my ignorance but when you say copy the directory you mean copy the files inside the folder extracted or the folder itself?(sorry again this time for my bad english)

**Comment by pinky28** [comment]
Follow the instruction given on ' https://github.com/vidyamantra/moodle-local_vmchat/wiki ' under "Installation in Moodle" heading.
OR
You can also instal it via zip file you have downloaded from Moodle plugin directory.
For detail visit-   https://docs.moodle.org/28/en/Installing_plugins and follow instruction given under ' Installing via uploaded ZIP file' .

**Comment by hizagi** [comment]
ok, thanks, already done :D
